####
#### Payload
#### by Jonah Seguin
####
name: Payload
main: com.jonahseguin.payload.PayloadPlugin
version: ${project.version}
author: Jonah Seguin
website: jonahseguin.com & github.com/jonahseguin/Payload
description: fail-safe asynchronous profile & object caching for spigot servers
api-version: 1.17

commands:
  payload:
    usage: '/payload'
    description: 'Main payload command.  See /payload help for sub-commands.'

permissions:
  payload.debug:
    default: op
  payload.admin:
    default: op